apiVersion: v1
kind: ServiceAccount
metadata:
  name: llmproxy
  namespace: llmproxy
  labels:
    app.kubernetes.io/name: llmproxy
    app.kubernetes.io/component: runtime
    app.kubernetes.io/part-of: llmproxy
    app.kubernetes.io/environment: base
